## Machine Learning

### Creating a logistic regression to predict absenteeism

In [1]:
# import relevant libraries
import numpy as np
import pandas as pd

In [2]:
# load the data
data_preprocessed = pd.read_csv('../data/preprocessed.csv')
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Year Month        Day  \
0           0         0         0         1  2015  July    Tuesday   
1           0         0         0         0  2015  July    Tuesday   
2           0         0         0         1  2015  July  Wednesday   
3           1         0         0         0  2015  July   Thursday   
4           0         0         0         1  2015  July   Thursday   
..        ...       ...       ...       ...   ...   ...        ...   
695         1         0         0         0  2018   May  Wednesday   
696         1         0         0         0  2018   May  Wednesday   
697         1         0         0         0  2018   May   Thursday   
698         0         0         0         1  2018   May   Thursday   
699         0         0         0         1  2018   May   Thursday   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                 30          0         2     1                          4  
1                 31          0         1     0                          0  
2                 31          0         0     0                          2  
3                 24          0         2     0                          4  
4                 30          0         2     1                          2  
..               ...        ...       ...   ...                        ...  
695               22          1         2     0                          8  
696               24          0         1     2                          3  
697               25          1         0     0                          8  
698               25          1         0     0                          2  
699               25          0         1     1                          2  

[700 rows x 16 columns]

### Create the targets

In [3]:
# using logistics regression
# creating classes; moderately absent, excessively absent
# using the median vlaue of the 'Absenteeism Time in Hours' as a cut-off line
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
# moderately absent (<= 3hours), excessively absent(>= 4 hours)
# moderately absent = 0, excessively absent = 1
# create a variable to predict this targets (0 & 1)
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                    data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
# add the target data to the dataframe
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Year Month        Day  \
0         0         0         0         1  2015  July    Tuesday   
1         0         0         0         0  2015  July    Tuesday   
2         0         0         0         1  2015  July  Wednesday   
3         1         0         0         0  2015  July   Thursday   
4         0         0         0         1  2015  July   Thursday   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [6]:
# checking the targets distribution
targets.sum() / targets.shape[0]

0.45571428571428574

In [7]:
# dropping the absentism column
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis = 1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Year Month        Day  \
0         0         0         0         1  2015  July    Tuesday   
1         0         0         0         0  2015  July    Tuesday   
2         0         0         0         1  2015  July  Wednesday   
3         1         0         0         0  2015  July   Thursday   
4         0         0         0         1  2015  July   Thursday   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

## Selecting the inputs for the regression

In [8]:
data_with_targets.shape

(700, 16)

In [9]:
# selecting the inputs excluding the last column 'extreme absenteeism'
unscaled_inputs = data_with_targets.iloc[:, :-1]
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Year Month        Day  \
0           0         0         0         1  2015  July    Tuesday   
1           0         0         0         0  2015  July    Tuesday   
2           0         0         0         1  2015  July  Wednesday   
3           1         0         0         0  2015  July   Thursday   
4           0         0         0         1  2015  July   Thursday   
..        ...       ...       ...       ...   ...   ...        ...   
695         1         0         0         0  2018   May  Wednesday   
696         1         0         0         0  2018   May  Wednesday   
697         1         0         0         0  2018   May   Thursday   
698         0         0         0         1  2018   May   Thursday   
699         0         0         0         1  2018   May   Thursday   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 15 columns]

## Standardize the Data

In [10]:
from sklearn.preprocessing import StandardScaler

# create an object to subtract the mean and divide by the SD featurewise
absenteeism_scalar = StandardScaler()

In [11]:
# before using standardscaler, lets convert 'month' and 'day' to integers
unscaled_inputs['Month'] = unscaled_inputs['Month'].replace(['January', 'February', 'March', 'April', 'May', 'June', 
'July', 'August', 'September', 'October', 'November', 'December'], ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'])
unscaled_inputs['Day'] = unscaled_inputs['Day'].replace(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 
'Sunday'], ['1', '2', '3', '4', '5', '6', '7'])
unscaled_inputs.head(9)

Reason_1  Reason_2  Reason_3  Reason_4  Year Month Day  \
0         0         0         0         1  2015     7   2   
1         0         0         0         0  2015     7   2   
2         0         0         0         1  2015     7   3   
3         1         0         0         0  2015     7   4   
4         0         0         0         1  2015     7   4   
5         0         0         0         1  2015     7   5   
6         0         0         0         1  2015     7   5   
7         0         0         0         1  2015     7   5   
8         0         0         1         0  2015     7   1   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   
6                     361                52   28                  239.554   
7                     260                50   36                  239.554   
8                     155                12   34                  239.554   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1  
5               31          0         0     0  
6               27          0         1     4  
7               23          0         4     0  
8               25          0         2     0

In [12]:
# fit input data (calculate and store the mean and SD)
absenteeism_scalar.fit(unscaled_inputs)

StandardScaler()

In [13]:
# transforming the unscaled inputs with the information contained in the absenteeism scalar. ie subtracting by the mean and dividing by the SD
scaled_inputs = absenteeism_scalar.transform(unscaled_inputs)
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

### Spilt the data into train & test and shuffle

In [14]:
#import relevant modules
from sklearn.model_selection import train_test_split


In [15]:
train_test_split(scaled_inputs, targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  2.8430157 ],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
          0.88046927, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -

above output consists of:
array 1: a training dataset with inputs
array 2: a training dataset with targets
array 3: a test dataset with inputs
array 4: a test dataset with targets

In [16]:
# declare four variables to contain the split outputs
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20) 

In [17]:
# view output shapes
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)


(560, 15) (560,)
(140, 15) (140,)


## Logistic regression with sklearn

In [18]:
from sklearn.linear_model import LogisticRegression
#for model evaluation
from sklearn import metrics

### Training the model

In [19]:
#declare a logistic regression object
reg = LogisticRegression()

In [20]:
# fitting the regression
reg.fit(x_train,y_train)

LogisticRegression()

In [21]:
# evaluating model accuracy
reg.score(x_train,y_train)

0.7821428571428571

### Manually check the accuracy

In [22]:
# find the outputs 
model_outputs = reg.predict(x_train)
model_outputs # shows the prediction of the model

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [23]:
# and compare with the targets
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [24]:
# calculate the number of correct predictions
np.sum((model_outputs==y_train))

438

In [25]:
# number of outputs
model_outputs.shape[0]

560

In [26]:
# Accuracy = Correct predictions / # observations
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7821428571428571

to use this model outside of python (Tableau), we need to create a function, to enable easy usuage within Tableau

#### Finding the intercept and coefficients

In [27]:
# finding intercept
reg.intercept_

array([-0.22277132])

In [28]:
#finding the coefficient
reg.coef_

array([[ 2.10337644,  0.34723084,  1.5508981 ,  1.34244762, -0.27312897,
         0.0504259 , -0.06908624,  0.70277574, -0.05690704, -0.18693736,
        -0.08235795,  0.32811835, -0.09568774,  0.36763007, -0.31765953]])

In [29]:
# to know the variable these variables refer to
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Year', 'Month',
       'Day', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [30]:
# best practice to define a variale to contain this info
feature_name = unscaled_inputs.columns.values

In [31]:
#creating a dataframe to contain the feature_names and the corresponding coefficient
summary_table = pd.DataFrame (columns=['feature name'], data = feature_name)

# matching the names with the coeffiecient
summary_table['Coefficient'] =np.transpose(reg.coef_) #transpose because ndarrays are rows not columns
summary_table

feature name  Coefficient
0                  Reason_1     2.103376
1                  Reason_2     0.347231
2                  Reason_3     1.550898
3                  Reason_4     1.342448
4                      Year    -0.273129
5                     Month     0.050426
6                       Day    -0.069086
7    Transportation Expense     0.702776
8          Distance to Work    -0.056907
9                       Age    -0.186937
10  Daily Work Load Average    -0.082358
11          Body Mass Index     0.328118
12                Education    -0.095688
13                 Children     0.367630
14                     Pets    -0.317660

In [32]:
# appending the intercept
# to shift the index of thee summary table so that the intercept comes first
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

feature name  Coefficient
0                 intercept    -0.222771
1                  Reason_1     2.103376
2                  Reason_2     0.347231
3                  Reason_3     1.550898
4                  Reason_4     1.342448
5                      Year    -0.273129
6                     Month     0.050426
7                       Day    -0.069086
8    Transportation Expense     0.702776
9          Distance to Work    -0.056907
10                      Age    -0.186937
11  Daily Work Load Average    -0.082358
12          Body Mass Index     0.328118
13                Education    -0.095688
14                 Children     0.367630
15                     Pets    -0.317660